---
- name: Create users ssh-keys when they do not exist
  user:
    name: "{{ user.name }}"
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_comment: "{{ user.name }}@{{ inventory_hostname }}"
  when: "user.generate_ssh_key is defined and user.generate_ssh_key|bool"
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: Generate ssh public key of current user if it does not exist
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_comment: "{{ ansible_user }}@{{ inventory_hostname }}"

- name: Add authorized SSH keys for each user to enable passwordless ssh connection
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  loop: "{{ lookup('subelements', users, 'ssh_authorized_keys', {'skip_missing': True}, wantlist=True) }}" # yamllint disable-line

- name: Configure sshd
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: "0644"
  notify:
    - reload sshd

- name: Force all notified handlers to run at this point
  meta: flush_handlers
